In [50]:
# Loading the data

In [51]:
import numpy as np
import pandas as pd

In [52]:
df = pd.read_csv(r'/content/anime.csv')

In [53]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [54]:
#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [55]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [56]:
df.loc[4]['Title']

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

In [57]:
df['episodes'] = df['Title'].str.extract(r'\((\d+)\s*eps\)')

In [58]:
df['episodes'] = pd.to_numeric(df['episodes'])

In [59]:
anime_10 = df[df['episodes'] == 10].reset_index(drop=True)

In [60]:
print(f"Total anime with 10 episodes: {len(anime_10)}")

Total anime with 10 episodes: 3

In [61]:
print(anime_10[['Rank', 'Title', 'episodes']])

   Rank                                              Title  episodes
0     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...        10
1    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...        10
2    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...        10

In [62]:
df['episodes'] = df['Title'].str.extract(r'(\(\d+\s*eps\))')

In [63]:
print(df['episodes'].to_string(index=False))

 (64 eps)
 (24 eps)
 (13 eps)
 (51 eps)
 (10 eps)
 (51 eps)
  (1 eps)
(148 eps)
 (13 eps)
 (13 eps)
  (2 eps)
(110 eps)
 (13 eps)
 (13 eps)
 (12 eps)
(201 eps)
  (1 eps)
 (22 eps)
 (24 eps)
 (25 eps)
  (1 eps)
  (1 eps)
  (7 eps)
 (14 eps)
 (74 eps)
  (1 eps)
  (1 eps)
 (12 eps)
  (1 eps)
 (24 eps)
 (23 eps)
 (12 eps)
 (26 eps)
 (13 eps)
 (16 eps)
 (11 eps)
  (1 eps)
 (11 eps)
 (10 eps)
  (1 eps)
 (26 eps)
 (12 eps)
 (75 eps)
 (26 eps)
 (26 eps)
 (24 eps)
 (10 eps)
 (12 eps)
 (12 eps)
  (4 eps)

In [64]:
def extract_eps(txt):
  check = False
  data = ""
  for i in txt:
    if i == ')':
      check = False
    if check == True:
      data = data + i
    if i == '(':
      check = True
  return data  # ✅ now it works

In [65]:
df["Episodes"] = df['Title'].apply(extract_eps)

In [66]:
df["Episodes"] = df["Episodes"].str.replace("eps", "")

In [67]:
df

,Rank,Title,Score,episodes,Episodes
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,(64 eps),64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,(24 eps),24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,(13 eps),13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,(51 eps),51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,(10 eps),10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,(51 eps),51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,(1 eps),1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,(148 eps),148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,(13 eps),13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,(13 eps),13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,(2 eps),2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,(110 eps),110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,(13 eps),13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,(13 eps),13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,(12 eps),12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,(201 eps),201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,(1 eps),1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,(22 eps),22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,(24 eps),24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,(25 eps),25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,(1 eps),1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,(1 eps),1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,(7 eps),7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,(14 eps),14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,(74 eps),74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,(1 eps),1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,(1 eps),1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,(12 eps),12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,(1 eps),1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,(24 eps),24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,(23 eps),23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,(12 eps),12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,(26 eps),26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,(13 eps),13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,(16 eps),16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,(11 eps),11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,(1 eps),1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,(11 eps),11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,(10 eps),10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,(1 eps),1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,(26 eps),26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,(12 eps),12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,(75 eps),75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,(26 eps),26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,(26 eps),26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,(24 eps),24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,(10 eps),10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,(12 eps),12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,(12 eps),12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,(4 eps),4

In [68]:
type(df.loc[0]['Episodes'])

str

In [69]:
df['Episodes'] = df['Episodes'].astype(int)

In [70]:
df

,Rank,Title,Score,episodes,Episodes
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,(64 eps),64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,(24 eps),24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,(13 eps),13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,(51 eps),51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,(10 eps),10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,(51 eps),51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,(1 eps),1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,(148 eps),148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,(13 eps),13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,(13 eps),13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,(2 eps),2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,(110 eps),110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,(13 eps),13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,(13 eps),13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,(12 eps),12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,(201 eps),201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,(1 eps),1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,(22 eps),22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,(24 eps),24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,(25 eps),25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,(1 eps),1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,(1 eps),1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,(7 eps),7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,(14 eps),14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,(74 eps),74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,(1 eps),1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,(1 eps),1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,(12 eps),12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,(1 eps),1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,(24 eps),24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,(23 eps),23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,(12 eps),12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,(26 eps),26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,(13 eps),13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,(16 eps),16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,(11 eps),11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,(1 eps),1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,(11 eps),11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,(10 eps),10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,(1 eps),1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,(26 eps),26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,(12 eps),12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,(75 eps),75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,(26 eps),26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,(26 eps),26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,(24 eps),24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,(10 eps),10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,(12 eps),12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,(12 eps),12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,(4 eps),4

In [71]:
def extract_time(txt):
   check = False
   data = ""
   for i in range(len(txt)):
     if txt[i] == ")":
        for j in range(i+1, i+20):
         data += txt[j]
        return data

In [72]:
df["Total Time"] = df["Title"].apply(extract_time)

In [73]:
df

,Rank,Title,Score,episodes,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,(64 eps),64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,(24 eps),24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,(13 eps),13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,(51 eps),51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,(10 eps),10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,(51 eps),51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,(1 eps),1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,(148 eps),148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,(13 eps),13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,(13 eps),13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,(2 eps),2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,(110 eps),110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,(13 eps),13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,(13 eps),13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,(12 eps),12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,(201 eps),201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,(1 eps),1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,(22 eps),22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,(24 eps),24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,(25 eps),25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,(1 eps),1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,(1 eps),1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,(7 eps),7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,(14 eps),14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,(74 eps),74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,(1 eps),1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,(1 eps),1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,(12 eps),12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,(1 eps),1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,(24 eps),24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,(23 eps),23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,(12 eps),12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,(26 eps),26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,(13 eps),13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,(16 eps),16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,(11 eps),11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,(1 eps),1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,(11 eps),11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,(10 eps),10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,(1 eps),1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,(26 eps),26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,(12 eps),12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,(75 eps),75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,(26 eps),26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,(26 eps),26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,(24 eps),24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,(10 eps),10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,(12 eps),12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,(12 eps),12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,(4 eps),4,Feb 1999 - Sep 1999

In [74]:
df

,Rank,Title,Score,episodes,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,(64 eps),64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,(24 eps),24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,(13 eps),13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,(51 eps),51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,(10 eps),10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,(51 eps),51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,(1 eps),1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,(148 eps),148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,(13 eps),13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,(13 eps),13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,(2 eps),2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,(110 eps),110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,(13 eps),13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,(13 eps),13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,(12 eps),12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,(201 eps),201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,(1 eps),1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,(22 eps),22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,(24 eps),24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,(25 eps),25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,(1 eps),1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,(1 eps),1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,(7 eps),7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,(14 eps),14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,(74 eps),74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,(1 eps),1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,(1 eps),1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,(12 eps),12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,(1 eps),1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,(24 eps),24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,(23 eps),23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,(12 eps),12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,(26 eps),26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,(13 eps),13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,(16 eps),16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,(11 eps),11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,(1 eps),1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,(11 eps),11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,(10 eps),10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,(1 eps),1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,(26 eps),26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,(12 eps),12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,(75 eps),75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,(26 eps),26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,(26 eps),26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,(24 eps),24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,(10 eps),10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,(12 eps),12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,(12 eps),12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,(4 eps),4,Feb 1999 - Sep 1999

In [75]:
df['start'] = pd.to_datetime(df['Total Time'].str.split(' - ').str[0])
df['end'] = pd.to_datetime(df['Total Time'].str.split(' - ').str[1])

df['months'] = (df['end'].dt.year - df['start'].dt.year) * 12 + (df['end'].dt.month - df['start'].dt.month)

/tmp/ipykernel_1959/1150697167.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['start'] = pd.to_datetime(df['Total Time'].str.split(' - ').str[0])
/tmp/ipykernel_1959/1150697167.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['end'] = pd.to_datetime(df['Total Time'].str.split(' - ').str[1])

In [76]:
df["Months"] = df['months'] + 1

In [77]:
df

,Rank,Title,Score,episodes,Episodes,Total Time,start,end,months,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,(64 eps),64,Apr 2009 - Jul 2010,2009-04-01,2010-07-01,15,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,(24 eps),24,Apr 2011 - Sep 2011,2011-04-01,2011-09-01,5,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,(13 eps),13,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,2,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,(51 eps),51,Apr 2015 - Mar 2016,2015-04-01,2016-03-01,11,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,(10 eps),10,Apr 2019 - Jul 2019,2019-04-01,2019-07-01,3,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,(51 eps),51,Apr 2011 - Mar 2012,2011-04-01,2012-03-01,11,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,(1 eps),1,Jan 2021 - Jan 2021,2021-01-01,2021-01-01,0,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,(148 eps),148,Oct 2011 - Sep 2014,2011-10-01,2014-09-01,35,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,(13 eps),13,Apr 2022 - Jun 2022,2022-04-01,2022-06-01,2,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,(13 eps),13,Oct 2012 - Mar 2013,2012-10-01,2013-03-01,5,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,(2 eps),2,Mar 2023 - May 2023,2023-03-01,2023-05-01,2,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,(110 eps),110,Jan 1988 - Mar 1997,1988-01-01,1997-03-01,110,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,(13 eps),13,Jul 2023 - Aug 2023,2023-07-01,2023-08-01,1,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,(13 eps),13,Apr 2021 - Jun 2021,2021-04-01,2021-06-01,2,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,(12 eps),12,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,2,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,(201 eps),201,Apr 2006 - Mar 2010,2006-04-01,2010-03-01,47,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,(1 eps),1,Sep 2016 - Sep 2016,2016-09-01,2016-09-01,0,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,(22 eps),22,Oct 2017 - Mar 2018,2017-10-01,2018-03-01,5,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,(24 eps),24,Oct 2008 - Mar 2009,2008-10-01,2009-03-01,5,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,(25 eps),25,Apr 2008 - Sep 2008,2008-04-01,2008-09-01,5,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,(1 eps),1,Jul 2013 - Jul 2013,2013-07-01,2013-07-01,0,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,(1 eps),1,Sep 2020 - Sep 2020,2020-09-01,2020-09-01,0,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,(7 eps),7,Aug 2017 - Aug 2017,2017-08-01,2017-08-01,0,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,(14 eps),14,Jul 2018 - Oct 2018,2018-07-01,2018-10-01,3,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,(74 eps),74,Apr 2004 - Sep 2005,2004-04-01,2005-09-01,17,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,(1 eps),1,Aug 2016 - Aug 2016,2016-08-01,2016-08-01,0,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,(1 eps),1,Dec 2022 - Dec 2022,2022-12-01,2022-12-01,0,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,(12 eps),12,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,2,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,(1 eps),1,Dec 2022 - Dec 2022,2022-12-01,2022-12-01,0,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,(24 eps),24,Jan 2023 - Jun 2023,2023-01-01,2023-06-01,5,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,(23 eps),23,Jul 2023 - Aug 2023,2023-07-01,2023-08-01,1,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,(12 eps),12,Jan 2018 - Mar 2018,2018-01-01,2018-03-01,2,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,(26 eps),26,Apr 2020 - Oct 2021,2020-04-01,2021-10-01,18,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,(13 eps),13,Jan 2019 - Apr 2019,2019-01-01,2019-04-01,3,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,(16 eps),16,Dec 2020 - Mar 2021,2020-12-01,2021-03-01,3,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,(11 eps),11,Dec 2021 - Feb 2022,2021-12-01,2022-02-01,2,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,(1 eps),1,Jan 2017 - Jan 2017,2017-01-01,2017-01-01,0,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,(11 eps),11,Apr 2023 - Jun 2023,2023-04-01,2023-06-01,2,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,(10 eps),10,Oct 2016 - Dec 2016,2016-10-01,2016-12-01,2,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,(1 eps),1,Jul 2001 - Jul 2001,2001-07-01,2001-07-01,0,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,(26 eps),26,Jul 2013 - Dec 2013,2013-07-01,2013-12-01,5,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,(12 eps),12,Jan 2022 - Apr 2022,2022-01-01,2022-04-01,3,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,(75 eps),75,Oct 2000 - Mar 2002,2000-10-01,2002-03-01,17,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,(26 eps),26,Apr 1998 - Apr 1999,1998-04-01,1999-04-01,12,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,(26 eps),26,Apr 2022 - Oct 2022,2022-04-01,2022-10-01,6,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,(24 eps),24,Jul 2019 - Dec 2019,2019-07-01,2019-12-01,5,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,(10 eps),10,Oct 2014 - Dec 2014,2014-10-01,2014-12-01,2,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,(12 eps),12,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,2,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,(12 eps),12,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,2,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,(4 eps),4,Feb 1999 - Sep 1999,1999-02-01,1999-09-01,7,8

In [78]:
df = df.drop(columns= ["start", "end"])

In [79]:
df

,Rank,Title,Score,episodes,Episodes,Total Time,months,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,(64 eps),64,Apr 2009 - Jul 2010,15,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,(24 eps),24,Apr 2011 - Sep 2011,5,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,(13 eps),13,Oct 2022 - Dec 2022,2,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,(51 eps),51,Apr 2015 - Mar 2016,11,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,(10 eps),10,Apr 2019 - Jul 2019,3,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,(51 eps),51,Apr 2011 - Mar 2012,11,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,(1 eps),1,Jan 2021 - Jan 2021,0,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,(148 eps),148,Oct 2011 - Sep 2014,35,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,(13 eps),13,Apr 2022 - Jun 2022,2,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,(13 eps),13,Oct 2012 - Mar 2013,5,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,(2 eps),2,Mar 2023 - May 2023,2,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,(110 eps),110,Jan 1988 - Mar 1997,110,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,(13 eps),13,Jul 2023 - Aug 2023,1,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,(13 eps),13,Apr 2021 - Jun 2021,2,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,(12 eps),12,Jan 2017 - Mar 2017,2,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,(201 eps),201,Apr 2006 - Mar 2010,47,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,(1 eps),1,Sep 2016 - Sep 2016,0,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,(22 eps),22,Oct 2017 - Mar 2018,5,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,(24 eps),24,Oct 2008 - Mar 2009,5,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,(25 eps),25,Apr 2008 - Sep 2008,5,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,(1 eps),1,Jul 2013 - Jul 2013,0,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,(1 eps),1,Sep 2020 - Sep 2020,0,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,(7 eps),7,Aug 2017 - Aug 2017,0,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,(14 eps),14,Jul 2018 - Oct 2018,3,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,(74 eps),74,Apr 2004 - Sep 2005,17,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,(1 eps),1,Aug 2016 - Aug 2016,0,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,(1 eps),1,Dec 2022 - Dec 2022,0,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,(12 eps),12,Oct 2022 - Dec 2022,2,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,(1 eps),1,Dec 2022 - Dec 2022,0,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,(24 eps),24,Jan 2023 - Jun 2023,5,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,(23 eps),23,Jul 2023 - Aug 2023,1,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,(12 eps),12,Jan 2018 - Mar 2018,2,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,(26 eps),26,Apr 2020 - Oct 2021,18,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,(13 eps),13,Jan 2019 - Apr 2019,3,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,(16 eps),16,Dec 2020 - Mar 2021,3,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,(11 eps),11,Dec 2021 - Feb 2022,2,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,(1 eps),1,Jan 2017 - Jan 2017,0,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,(11 eps),11,Apr 2023 - Jun 2023,2,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,(10 eps),10,Oct 2016 - Dec 2016,2,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,(1 eps),1,Jul 2001 - Jul 2001,0,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,(26 eps),26,Jul 2013 - Dec 2013,5,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,(12 eps),12,Jan 2022 - Apr 2022,3,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,(75 eps),75,Oct 2000 - Mar 2002,17,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,(26 eps),26,Apr 1998 - Apr 1999,12,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,(26 eps),26,Apr 2022 - Oct 2022,6,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,(24 eps),24,Jul 2019 - Dec 2019,5,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,(10 eps),10,Oct 2014 - Dec 2014,2,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,(12 eps),12,Jan 2017 - Mar 2017,2,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,(12 eps),12,Oct 2022 - Dec 2022,2,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,(4 eps),4,Feb 1999 - Sep 1999,7,8

In [82]:
df[df["Score"] == df["Score"].max()]["Title"]

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [83]:
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [84]:
df[df["Episodes"] == df["Episodes"].max()]

,Rank,Title,Score,episodes,Episodes,Total Time,months,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,(201 eps),201,Apr 2006 - Mar 2010,47,48