In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1:10, 2:20, 3:30}

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
# Creating a DataFrame
std_details = {
    "Name": ["Amit", "Sara", "John", "Priya"],
    "Age": [21, 22, 20, 23],
    "Branch": ["CSE", "ECE", "ME", "IT"],
    "City": ["Delhi", "Mumbai", "Bangalore", "Chennai"]
}
df = pd.DataFrame(std_details)

In [ ]:
df

    Name  Age Branch       City
0   Amit   21    CSE      Delhi
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
std_details1 = {
    1: ["Amit", 21, "CSE", "Delhi"],
    2: ["Sara", 22, "ECE", "Mumbai"],
    3: ["John", 20, "ME", "Bangalore"],
    4: ["Priya", 23, "IT", "Chennai"]
}
column = ['Name', 'Age', 'Branch', 'City']
df2 = pd.DataFrame(std_details1, columns = column)

In [ ]:
df2

Empty DataFrame
Columns: [Name, Age, Branch, City]
Index: []

In [ ]:
# Selection and Indexing of Columns
df

    Name  Age Branch       City
0   Amit   21    CSE      Delhi
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
df[['Name', 'Age']]

    Name  Age
0   Amit   21
1   Sara   22
2   John   20
3  Priya   23

In [ ]:
df["Designation"] = ['Doctor', 'Engineer', 'Teacher', 'Doctor']

In [ ]:
df

    Name  Age Branch       City Designation
0   Amit   21    CSE      Delhi      Doctor
1   Sara   22    ECE     Mumbai    Engineer
2   John   20     ME  Bangalore     Teacher
3  Priya   23     IT    Chennai      Doctor

In [ ]:
df.drop('Designation', axis = 1)

    Name  Age Branch       City
0   Amit   21    CSE      Delhi
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
df

    Name  Age Branch       City Designation
0   Amit   21    CSE      Delhi      Doctor
1   Sara   22    ECE     Mumbai    Engineer
2   John   20     ME  Bangalore     Teacher
3  Priya   23     IT    Chennai      Doctor

In [ ]:
df.drop('Designation', axis = 1, inplace = True)

In [ ]:
df

    Name  Age Branch       City
0   Amit   21    CSE      Delhi
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
df.drop(['Age', 'City'], axis = 1)

    Name Branch
0   Amit    CSE
1   Sara    ECE
2   John     ME
3  Priya     IT

In [ ]:
df

    Name  Age Branch       City
0   Amit   21    CSE      Delhi
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
df.drop(0, axis = 0)

    Name  Age Branch       City
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
df

    Name  Age Branch       City
0   Amit   21    CSE      Delhi
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
# Selecting a Row
df

    Name  Age Branch       City
0   Amit   21    CSE      Delhi
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
df.loc[[1,2]]

   Name  Age Branch       City
1  Sara   22    ECE     Mumbai
2  John   20     ME  Bangalore

In [ ]:
df.iloc[0] # iloc = Index Location

Name       Amit
Age          21
Branch      CSE
City      Delhi
Name: 0, dtype: object

In [ ]:
# Selecting Subset of rows and column
df.loc[[2, 3]][['Name', 'Branch']]

    Name Branch
2   John     ME
3  Priya     IT

In [ ]:
#Conditional Statement
df

    Name  Age Branch       City
0   Amit   21    CSE      Delhi
1   Sara   22    ECE     Mumbai
2   John   20     ME  Bangalore
3  Priya   23     IT    Chennai

In [ ]:
df[df['Age'] > 20]

    Name  Age Branch     City
0   Amit   21    CSE    Delhi
1   Sara   22    ECE   Mumbai
3  Priya   23     IT  Chennai

In [ ]:
df[(df['Age'] > 20) & (df['Branch'] == 'CSE')]

   Name  Age Branch   City
0  Amit   21    CSE  Delhi

In [ ]:
# Finding Missing data
data = {
    "A": ["Amit", 21, "CSE", "Delhi"],
    "B": ["Sara", 22, np.nan, np.nan],
    "C": ["Sam", np.nan, "ME", np.nan],
    "D": ["Priya", 23, np.nan, np.nan]
}

m = pd.DataFrame(data)

In [ ]:
m

       A     B    C      D
0   Amit  Sara  Sam  Priya
1     21    22  NaN     23
2    CSE   NaN   ME    NaN
3  Delhi   NaN  NaN    NaN

In [ ]:
m.isna()

       A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False   True  False   True
3  False   True   True   True

In [ ]:
m.isna().sum() # Check how many null value is in each column

A    0
B    2
C    2
D    2
dtype: int64

In [ ]:
m.isna().any() #Check each column have Null value

A    False
B     True
C     True
D     True
dtype: bool

In [ ]:
m.dropna()

      A     B    C      D
0  Amit  Sara  Sam  Priya

In [ ]:
m

       A     B    C      D
0   Amit  Sara  Sam  Priya
1     21    22  NaN     23
2    CSE   NaN   ME    NaN
3  Delhi   NaN  NaN    NaN

In [ ]:
m.dropna(thresh = 2) #Drop which row have 2 NaN

      A     B    C      D
0  Amit  Sara  Sam  Priya
1    21    22  NaN     23
2   CSE   NaN   ME    NaN

In [ ]:
# Fill missing data
m.fillna(0)

       A     B    C      D
0   Amit  Sara  Sam  Priya
1     21    22    0     23
2    CSE     0   ME      0
3  Delhi     0    0      0

In [ ]:
m

       A     B    C      D
0   Amit  Sara  Sam  Priya
1     21    22  NaN     23
2    CSE   NaN   ME    NaN
3  Delhi   NaN  NaN    NaN

In [ ]:
value = {'A':0, 'B': 10}
m.fillna(value = value)

       A     B    C      D
0   Amit  Sara  Sam  Priya
1     21    22  NaN     23
2    CSE    10   ME    NaN
3  Delhi    10  NaN    NaN

In [ ]:
m

       A     B    C      D
0   Amit  Sara  Sam  Priya
1     21    22  NaN     23
2    CSE   NaN   ME    NaN
3  Delhi   NaN  NaN    NaN

In [ ]:
std = {
    "A": [101, 21, np.nan, 4001],   # nan at index 2
    "B": [102, np.nan, 3002, 4002], # nan at index 1
    "C": [np.nan, 20, 3003, 4003],  # nan at index 0
    "D": [104, 23, 3004, np.nan]    # nan at index 3
}

df1 = pd.DataFrame(std)

In [ ]:
df1

        A       B       C       D
0   101.0   102.0     NaN   104.0
1    21.0     NaN    20.0    23.0
2     NaN  3002.0  3003.0  3004.0
3  4001.0  4002.0  4003.0     NaN

In [ ]:
df1.fillna(df1.mean()) #Like this you can take mean

             A            B       C            D
0   101.000000   102.000000  2342.0   104.000000
1    21.000000  2368.666667    20.0    23.000000
2  1374.333333  3002.000000  3003.0  3004.000000
3  4001.000000  4002.000000  4003.0  1043.666667

In [ ]:
employees = pd. DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
    })
# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
    })

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
# Merging two Data Frames
pd.merge(employees, salaries, on = 'employee_id', how = 'inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees, salaries, on = 'employee_id', how = 'outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees, salaries, on = 'employee_id', how = 'left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees, salaries, on = 'employee_id', how = 'right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [ ]:
df1 = pd.DataFrame({ 'Α': ['Α0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2'], 'C': ['C0', 'C1', 'C2']
})
df2 = pd.DataFrame({ 'A': ['A3', 'A4', 'A5'], 'B': ['B3', 'B4', '85'], 'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    Α   B   C
0  Α0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  85  C5

In [ ]:
# Concatenation of two DataFrames
pd.concat([df1, df2])

     Α   B   C    A
0   Α0  B0  C0  NaN
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
0  NaN  B3  C3   A3
1  NaN  B4  C4   A4
2  NaN  85  C5   A5

In [ ]:
pd.concat([df1, df2], axis = 1)

    Α   B   C   A   B   C
0  Α0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  85  C5

In [ ]:
df1 = pd.DataFrame({ 'name': ['Alice', 'Bob', 'Charlie'] }, index=[1, 2, 3])
# Second DataFrame
df2 = pd.DataFrame({ 'score': [85, 90, 75] }, index=[2, 3, 4])

In [ ]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
df2

   score
2     85
3     90
4     75

In [ ]:
# Joining of two DataFrames
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
df1.join(df2, how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [ ]:
# Group By Aggregation
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
 # Group by category and calc the sum of sales
 cat = df.groupby('Category')['Sales'].sum()
 cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
# Group by store and calculate the sum of sales
store = df.groupby('Store')['Sales'].sum()
store

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
# Group by multiple columns
# Group by Category and Stores
g = df.groupby(['Category', 'Store'])['Sales'].sum()
g

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [ ]:
# Aggregation - Combine multiple things and get one answer
df['Sales'].mean()

np.float64(187.5)

In [ ]:
h = df['Sales'].agg(['sum', 'count', 'mean', 'median', 'min', 'max', 'std'])
h

sum       1500.000000
count        8.000000
mean       187.500000
median     190.000000
min        100.000000
max        300.000000
std         66.062741
Name: Sales, dtype: float64

***Pivot Tables***

In [ ]:
data = {
    'Date': pd.date_range('2024-01-01', periods=20),

    'Product': [
        'Laptop', 'Mobile', 'Tablet', 'Headphones'
    ] * 5,

    'Region': [
        'North', 'South', 'East', 'West',
        'North', 'South', 'East', 'West',
        'North', 'South', 'East', 'West',
        'North', 'South', 'East', 'West',
        'North', 'South', 'East', 'West'
    ],

    'Sales': np.random.randint(100, 1000, 20),

    'Units': np.random.randint(1, 10, 20),

    'Salesperson': [
        'Rahul', 'Priya', 'Amit', 'Neha'
    ] * 5
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [ ]:
df

         Date     Product Region  Sales  Units Salesperson    Month Quarter
0  2024-01-01      Laptop  North    345      7       Rahul  January      Q1
1  2024-01-02      Mobile  South    121      4       Priya  January      Q1
2  2024-01-03      Tablet   East    672      6        Amit  January      Q1
3  2024-01-04  Headphones   West    184      4        Neha  January      Q1
4  2024-01-05      Laptop  North    453      6       Rahul  January      Q1
5  2024-01-06      Mobile  South    870      9       Priya  January      Q1
6  2024-01-07      Tablet   East    784      8        Amit  January      Q1
7  2024-01-08  Headphones   West    988      9        Neha  January      Q1
8  2024-01-09      Laptop  North    387      2       Rahul  January      Q1
9  2024-01-10      Mobile  South    418      2       Priya  January      Q1
10 2024-01-11      Tablet   East    732      9        Amit  January      Q1
11 2024-01-12  Headphones   West    833      5        Neha  January      Q1
12 2024-01-13      Laptop  North    614      2       Rahul  January      Q1
13 2024-01-14      Mobile  South    742      7       Priya  January      Q1
14 2024-01-15      Tablet   East    405      3        Amit  January      Q1
15 2024-01-16  Headphones   West    842      6        Neha  January      Q1
16 2024-01-17      Laptop  North    362      4       Rahul  January      Q1
17 2024-01-18      Mobile  South    841      4       Priya  January      Q1
18 2024-01-19      Tablet   East    274      9        Amit  January      Q1
19 2024-01-20  Headphones   West    940      7        Neha  January      Q1

In [ ]:
pd.pivot_table(df, values = 'Sales', index = 'Region', columns = 'Product', aggfunc = 'max')

Product  Headphones  Laptop  Mobile  Tablet
Region
East            NaN     NaN     NaN   784.0
North           NaN   614.0     NaN     NaN
South           NaN     NaN   870.0     NaN
West          988.0     NaN     NaN     NaN

In [ ]:
pivot2 = pd.pivot_table(df, values = ['Sales', 'Units'], index = 'Region', columns = 'Product', aggfunc = 'sum')

In [ ]:
pivot2

             Sales                              Units
Product Headphones  Laptop  Mobile  Tablet Headphones Laptop Mobile Tablet
Region
East           NaN     NaN     NaN  2867.0        NaN    NaN    NaN   35.0
North          NaN  2161.0     NaN     NaN        NaN   21.0    NaN    NaN
South          NaN     NaN  2992.0     NaN        NaN    NaN   26.0    NaN
West        3787.0     NaN     NaN     NaN       31.0    NaN    NaN    NaN

**Cross Table**

In [ ]:
pd.crosstab(df['Region'], df['Product'])

Product  Headphones  Laptop  Mobile  Tablet
Region
East              0       0       0       5
North             0       5       0       0
South             0       0       5       0
West              5       0       0       0

**Operations**

In [ ]:
d = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
d

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
d.shape

(5, 3)

In [ ]:
d.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
d.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
d['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**DataFrame applying Functions**

In [ ]:
d

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
def square(x):
  return x**2

In [ ]:
d['D'] = d['B'].apply(square)

In [ ]:
d

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000

In [ ]:
d['B'] = d['B'].apply(lambda x: x**2) #using lambda

In [ ]:
d

   A        B    C        D
0  1    10000  100    10000
1  2   160000  200   160000
2  3   810000  300   810000
3  4  2560000  400  2560000
4  5  6250000  500  6250000